# Generated by Django 5.1.1 on 2024-09-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', help_text='Укажите фамилию', max_length=60, null=True, verbose_name='Фамилия'),
        ),
    ]
