# Generated by Django 5.1.1 on 2024-09-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Иван', help_text='Укажите имя', max_length=60, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Иванов', help_text='Укажите фамилию', max_length=60, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='+79991234567', help_text='Укажите телефон начиная с +7', max_length=15, verbose_name='Телефон'),
        ),
    ]
