services:

  db:
    image: postgres
    restart: on-failure
    env_file:
      - .env
    expose:
      - '5432'
    volumes:
      - api_data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', '-c', 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB' ]
      interval: 1s
      retries: 2
      timeout: 1s

  app:
    build: .
    tty: true
    ports:
      - '8000:8000'
    command: sh -c 'python3 manage.py migrate && python3 manage.py collectstatic --noinput && gunicorn API_for_library_management.wsgi:application --bind 0.0.0.0:8000 --workers 3'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    env_file:
      - .env

  nginx:
    image: nginx
    restart: on-failure
    ports:
      - '80:80'
    volumes:
      - .:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Ваш файл конфигурации
    depends_on:
      - app  # Зависимость от приложения, чтобы оно было доступно

volumes:
  api_data: