# Generated by Django 5.1.1 on 2024-09-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name'], 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, help_text='Введите текст биографии', null=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Введите дату рождения, в формате ГОД-МЕСЯЦ-ДЕНЬ', null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(help_text='Введите полное Ф. И. О. автора книги', max_length=255, verbose_name='Ф. И. О. автора книги'),
        ),
    ]
