# Generated by Django 5.1.1 on 2024-09-21 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_author_options_alter_author_bio_and_more'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(help_text='Выберите автора книги', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='authors.author', verbose_name='Автор книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, help_text='Введите описание книги', null=True, verbose_name='Описание книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, help_text='Введите жанр книги', max_length=100, null=True, verbose_name='Жанр книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, help_text='Введите ISBN книги', max_length=13, null=True, unique=True, verbose_name='ISBN книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(blank=True, help_text='Введите дату публикации книги', null=True, verbose_name='Дата публикации книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Введите название книги', max_length=255, verbose_name='Название книги'),
        ),
    ]
