# Generated by Django 5.1.1 on 2024-09-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='count',
            field=models.PositiveIntegerField(default=1, help_text='Введите количество книг в наличии', verbose_name='Количество книг'),
        ),
    ]
