# Generated by Django 5.1.1 on 2024-09-21 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_options_alter_book_author_and_more'),
        ('relbooks', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField(auto_now_add=True, help_text='Введите дату выдачи книги', verbose_name='Дата выдачи')),
                ('return_date', models.DateField(blank=True, help_text='Введите дату возврата книги', null=True, verbose_name='Дата возврата')),
                ('book', models.ForeignKey(help_text='Выберите книгу', on_delete=django.db.models.deletion.CASCADE, related_name='relbooks', to='books.book', verbose_name='Книга')),
                ('user', models.ForeignKey(help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='relbooks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Выдача книги',
                'verbose_name_plural': 'Выдачи книг',
                'ordering': ['book'],
            },
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
